### ISSUE TITLE
changeTodoStatus Warning: commitRelayModernMutation: Expected `optimisticResponse` to be an object, received a function.

### ISSUE THREAD

**Issue by moolo** [relayjs/relay-examples#42] opened 2017-07-29 11:28 UTC
changeTodoStatus
 Warning: commitRelayModernMutation: Expected `optimisticResponse` to be an object, received a function.

**Comment by kassens** [comment] 2017-08-29 01:40
Thanks, duplicate of #41

**Closed by kassens** 2017-08-29 01:40 UTC
